"""Produce Mockingbird-generated events into local Kafka."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from confluent_kafka import KafkaException, Producer

from streaming_tutorial.config import DEFAULT_TOPIC, defaults_from_env

KEY_CANDIDATES = (
    "user_id",
    "session_id",
    "stock_symbol",
    "order_id",
    "booking_id",
    "id",
)


def project_root() -> Path:
    return Path(__file__).resolve().parents[2]


def build_parser() -> argparse.ArgumentParser:
    defaults = defaults_from_env()
    parser = argparse.ArgumentParser(
        prog="kafka-produce",
        description=(
            "Run the Mockingbird JSONL helper and publish each generated event "
            "to the local Kafka tutorial topic."
        ),
    )
    parser.add_argument(
        "--bootstrap-servers",
        default=defaults.bootstrap_servers,
        help=f"Kafka bootstrap servers. Default: {defaults.bootstrap_servers}",
    )
    parser.add_argument("--topic", default=defaults.topic, help=f"Topic name. Default: {DEFAULT_TOPIC}")
    parser.add_argument(
        "--template",
        default=defaults.template,
        help=f"Mockingbird preset template. Default: {defaults.template!r}",
    )
    parser.add_argument(
        "--eps",
        type=float,
        default=defaults.eps,
        help=f"Events per second generated by Mockingbird. Default: {defaults.eps}",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=defaults.limit,
        help=f"Number of events to produce. Use -1 to run until Ctrl-C. Default: {defaults.limit}",
    )
    parser.add_argument(
        "--client-id",
        default="mockingbird-python-producer",
        help="Kafka producer client.id used in broker/UI metadata.",
    )
    return parser


def build_generator_command(*, root: Path, template: str, eps: float, limit: int) -> list[str]:
    return [
        "node",
        str(root / "tools" / "mockingbird-jsonl.mjs"),
        "--template",
        template,
        "--eps",
        str(eps),
        "--limit",
        str(limit),
    ]


def parse_event_line(line: str) -> dict[str, Any]:
    try:
        event = json.loads(line)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Mockingbird emitted invalid JSON: {line[:120]!r}") from exc

    if not isinstance(event, dict):
        raise ValueError(f"Expected a JSON object from Mockingbird, received {type(event).__name__}")

    return event


def choose_message_key(event: dict[str, Any]) -> str | None:
    """Choose a stable-ish key so learners can see partition affinity.

    Mockingbird templates use different field names. Prefer identity fields when
    present, then fall back to domain identifiers such as stock symbols.
    """

    for field in KEY_CANDIDATES:
        value = event.get(field)
        if value is not None:
            return str(value)
    return None


def produce_events(
    *,
    bootstrap_servers: str,
    topic: str,
    template: str,
    eps: float,
    limit: int,
    client_id: str,
    root: Path | None = None,
) -> int:
    if eps <= 0:
        print("--eps must be greater than 0", file=sys.stderr)
        return 2
    if limit == 0 or limit < -1:
        print("--limit must be -1 or a positive integer", file=sys.stderr)
        return 2

    root = root or project_root()
    generator_command = build_generator_command(root=root, template=template, eps=eps, limit=limit)

    producer = Producer(
        {
            "bootstrap.servers": bootstrap_servers,
            "client.id": client_id,
            "acks": "all",
        }
    )

    delivery = {"ok": 0, "errors": 0}

    def on_delivery(error: KafkaException | None, message: Any) -> None:
        if error is not None:
            delivery["errors"] += 1
            print(f"delivery failed: {error}", file=sys.stderr)
            return

        delivery["ok"] += 1
        print(
            "delivered "
            f"topic={message.topic()} partition={message.partition()} "
            f"offset={message.offset()} key={message.key()!r}"
        )

    print("Starting Mockingbird generator:", " ".join(generator_command))
    process = subprocess.Popen(
        generator_command,
        cwd=root,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
    )

    produced = 0
    try:
        assert process.stdout is not None
        for line in process.stdout:
            line = line.strip()
            if not line:
                continue

            event = parse_event_line(line)
            key = choose_message_key(event)
            payload = json.dumps(event, separators=(",", ":"), default=str).encode("utf-8")

            while True:
                try:
                    producer.produce(topic, key=key, value=payload, on_delivery=on_delivery)
                    break
                except BufferError:
                    producer.poll(0.5)

            producer.poll(0)
            produced += 1
            print(f"queued event {produced}: key={key!r} value={payload.decode('utf-8')}")

    except KeyboardInterrupt:
        print("\nStopping producer and Mockingbird generator...", file=sys.stderr)
        process.terminate()
    finally:
        remaining = producer.flush(15)
        if remaining:
            print(f"WARNING: {remaining} message(s) were not delivered before timeout.", file=sys.stderr)

    return_code = process.wait(timeout=5)
    stderr = process.stderr.read() if process.stderr is not None else ""

    if return_code != 0:
        print(
            "Mockingbird generator failed. Did you run `npm install`?\n"
            f"Exit code: {return_code}\n{stderr}",
            file=sys.stderr,
        )
        return 1

    print(f"Finished. queued={produced} delivered={delivery['ok']} errors={delivery['errors']}")
    return 1 if delivery["errors"] else 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return produce_events(
        bootstrap_servers=args.bootstrap_servers,
        topic=args.topic,
        template=args.template,
        eps=args.eps,
        limit=args.limit,
        client_id=args.client_id,
    )


if __name__ == "__main__":
    raise SystemExit(main())
